// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXLK98aCqMdZadKJlq3oOI6OxRWS3u1Ic',
    appId: '1:316199379300:web:1a64ff63b9a2cade0d9a71',
    messagingSenderId: '316199379300',
    projectId: 'app-comunitaria-d396c',
    authDomain: 'app-comunitaria-d396c.firebaseapp.com',
    storageBucket: 'app-comunitaria-d396c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_8IouhAuSlss60fx6HT8Eb8Hi1yT_dYI',
    appId: '1:316199379300:android:50619aa92f52be320d9a71',
    messagingSenderId: '316199379300',
    projectId: 'app-comunitaria-d396c',
    storageBucket: 'app-comunitaria-d396c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClkaRlMR2oCbs4opXBVotp4kIQzBgOjY0',
    appId: '1:316199379300:ios:8038da225f70fe620d9a71',
    messagingSenderId: '316199379300',
    projectId: 'app-comunitaria-d396c',
    storageBucket: 'app-comunitaria-d396c.firebasestorage.app',
    iosBundleId: 'com.example.appComunitaria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClkaRlMR2oCbs4opXBVotp4kIQzBgOjY0',
    appId: '1:316199379300:ios:8038da225f70fe620d9a71',
    messagingSenderId: '316199379300',
    projectId: 'app-comunitaria-d396c',
    storageBucket: 'app-comunitaria-d396c.firebasestorage.app',
    iosBundleId: 'com.example.appComunitaria',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXLK98aCqMdZadKJlq3oOI6OxRWS3u1Ic',
    appId: '1:316199379300:web:fb09428d9be5e5470d9a71',
    messagingSenderId: '316199379300',
    projectId: 'app-comunitaria-d396c',
    authDomain: 'app-comunitaria-d396c.firebaseapp.com',
    storageBucket: 'app-comunitaria-d396c.firebasestorage.app',
  );
}
